<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="olympics" nsURI="http://se.lnu.mde/olympics/clean" nsPrefix="olympics">
  <eClassifiers xsi:type="ecore:EClass" name="OlympicGames">
    <eOperations name="addCommittee">
      <eParameters name="theCommittee" eType="#//InvitedCommittee"/>
    </eOperations>
    <eOperations name="addDiscipline">
      <eParameters name="theDiscipline" eType="#//Discipline"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitedcommittees" upperBound="-1"
        eType="#//InvitedCommittee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disciplines" upperBound="-1"
        eType="#//Discipline" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvitedCommittee">
    <eOperations name="addTeam">
      <eParameters name="theTeam" eType="#//Team"/>
    </eOperations>
    <eOperations name="addAthlete">
      <eParameters name="theAthlete" eType="#//Athlete"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToFlag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfGoldMedals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="athletes" upperBound="-1"
        eType="#//Athlete" containment="true" eOpposite="#//Athlete/invitedcommittee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="-1"
        eType="#//Team" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discipline">
    <eOperations name="addEvent">
      <eParameters name="theEvent" eType="#//Event"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Medalable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="winnerOf" upperBound="-1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Medalable">
    <eOperations name="addMember">
      <eParameters name="theAthlete" eType="#//Athlete"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teamMembers" upperBound="-1"
        eType="#//Athlete" eOpposite="#//Athlete/teamMembership"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Athlete" eSuperTypes="#//Medalable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teamMembership" upperBound="-1"
        eType="#//Team" eOpposite="#//Team/teamMembers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitedcommittee" eType="#//InvitedCommittee"
        eOpposite="#//InvitedCommittee/athletes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eOperations name="addParticipant">
      <eParameters name="theParticipiant" eType="#//Medalable"/>
    </eOperations>
    <eOperations name="getParticipants" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeamEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goldMedal" eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bronzeMedal" eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="silverMedal" eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Team"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goldMedal" eType="#//Athlete"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BronzeMedal" eType="#//Athlete"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="silverMedal" eType="#//Athlete"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Athlete"/>
  </eClassifiers>
</ecore:EPackage>
