<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="universityActivities" nsURI="http://www.example.org/universityActivities"
    nsPrefix="universityActivities">
  <eClassifiers xsi:type="ecore:EClass" name="UniversityActivities">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studyProgram" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lectures" lowerBound="1"
        upperBound="-1" eType="#//Lecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exams" lowerBound="1" upperBound="-1"
        eType="#//Exam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ExamType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecture">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalHours" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredExams" upperBound="-1"
        eType="#//Exam"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExamType">
    <eLiterals name="writtenExam"/>
    <eLiterals name="oralExam" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignmentNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedWorkloadInHours"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
