<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" 
	xmlns:xmi="http://www.omg.org/XMI" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" 
    name="projectStructureMM" 
    nsURI="http://www.g7.org/projectStructureMM"
    nsPrefix="projectStructureMM">
    
  <!-- Abstract FileSystemElement Class -->
  <eClassifiers xsi:type="ecore:EClass" name="FileSystemElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  
  <!-- Directory Class -->
  <eClassifiers xsi:type="ecore:EClass" name="Directory" eSuperTypes="#//FileSystemElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filesystemelement" upperBound="-1"
        eType="#//FileSystemElement" containment="true"/>
  </eClassifiers>
  
  <!-- File Class -->
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//FileSystemElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  
  <!-- Root Class: NotebookModel -->
  <eClassifiers xsi:type="ecore:EClass" name="ProjectStructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filesystemelement" upperBound="-1"
        eType="#//FileSystemElement"/>
  </eClassifiers>
</ecore:EPackage>
